### ISSUE TITLE
Could not find match for YAML element PackageFolders

### ISSUE THREAD

**Issue by MegaThorx** [modesttree/Projeny#14] opened 2016-02-18 19:32 UTC
Could someone help me out with this one.
Didn't find anything in the readme

```
# Default values
# These can all be overriden by user config files

MaxProjectNameLength: 10

# Set to true if you don't want to use the Projeny editor DLL and instead want to link directly
# to UnityPlugin\Projeny
LinkToProjenyEditorDir: False

ReleaseSources:
    - AssetStoreCache:

PathVars:
    ProjTemplatesDir: '[ProjenyDir]/Templates'

    CsProjectTemplate: '[ProjTemplatesDir]/CsProjectTemplate.csproj'
    CsSolutionTemplate: '[ProjTemplatesDir]/CsSolutionTemplate.sln'

    PlaceholderFile1: '[ProjTemplatesDir]/Placeholder1/Placeholder.cs'
    PlaceholderFile2: '[ProjTemplatesDir]/Placeholder2/Placeholder.cs'

    ProjenyChangeProjectMenuMeta: '[ProjTemplatesDir]/ProjenyChangeProjectMenu.cs.meta'

    ProjectRootGitIgnoreTemplate: '[ProjTemplatesDir]/customProjectRootGitIgnore'
    ProjectRootSvnIgnoreTemplate: '[ProjTemplatesDir]/customProjectRootSvnIgnore'

    YamlDotNetDllPath: '[ProjenyDir]/Bin/UnityPlugin/Release/YamlDotNet.dll'
    ProjenyUnityEditorDllPath: '[ProjenyDir]/Bin/UnityPlugin/Release/Projeny.dll'
    ProjenyUnityEditorDllMetaFilePath: '[ProjTemplatesDir]/Projeny.dll.meta'
    ProjenyUnityEditorAssetsDirPath: '[ProjenyDir]/UnityPlugin/Projeny/Assets'
    UnityProjectsDir: 'F:\Dateien\Unity\Projekte'


    # Note that these are defaults, and can be overridden in any other Projeny.yaml file
    MsBuildExePath: 'C:/Windows/Microsoft.NET/Framework/v4.0.30319/msbuild.exe'
    UnityExePath: 'C:/Program Files/Unity/Editor/Unity.exe'

Console:
    UseColors: False
    OutputToFilteredLog: False

Compilation:
    UseDevenv: False

IncludeProjenyInGeneratedSolution: False

```

```
C:\Program Files (x86)\Projeny>prj --project Test --createProject

Initializing new project "Test"...
   Updating package directories for project Test...
      Project "Test" is not initialized for platform "Windows".  Initializing now.
      Initializing new project Test (Windows)...
      Failed during task:  initializing new project Test (Windows) (Took 0.0 seconds, time: 20:29:56, total elapsed: 0.0 seconds)
   Failed during task:  updating package directories for project Test (Took 0.0 seconds, time: 20:29:56, total elapsed: 0.0 seconds)
Failed during task:  initializing new project "Test" (Took 0.0 seconds, time: 20:29:56, total elapsed: 0.0 seconds)
Failed while processing config yaml for project 'Test' (platform 'Windows'). Details: Error: Could not find match for YAML element PackageFolders
Operation completed with errors.  Took 0.0 seconds.
```

**Comment by svermeulen** [comment] 2016-02-18 19:47
You shouldn't run `prj` directly from the Projeny install directory.  The way its intended to be used is to add `C:\Program Files (x86)\Projeny\bin` to your windows PATH, and then execute `prj` in a new directory where you want to create your unity project, etc.

Did you try following the instructions [here](https://github.com/modesttree/Projeny#workflow-create-new-config)?

**Comment by svermeulen** [comment] 2016-02-18 20:03
If that link doesn't work just search for "How do I start an entirely new set of Projeny-based packages/projects from scratch?" in the docs

**Comment by MegaThorx** [comment] 2016-02-19 11:04
I didn't create a Projeny.yaml. I used the one from the installation folder :smile:. I will test it if i'm at home.

**Comment by MegaThorx** [comment] 2016-02-20 13:10
```
Started Prj with arguments: --project ModdingGameClient --createProject
--------------------------
Initializing new project "ModdingGameClient"...
--------------------------
Making missing directories in path 'F:\Dateien\Unity\Projekte/UnityProjects/ModdingGameClient\ProjenyProject.yaml'
--------------------------
Updating package directories for project ModdingGameClient...
--------------------------
Project "ModdingGameClient" is not initialized for platform "Windows".  Initializing now.
--------------------------
Initializing new project ModdingGameClient (Windows)...
--------------------------
Loading schema at path "F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ProjenyProject.yaml"
Processing dependency tree
Found 0 packages in total for given schema
Created directory "F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ModdingGam-Windows"
Making missing directories in path 'F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ModdingGam-Windows\ProjectSettings'
Making junction with actual path (F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ModdingGam-Windows\ProjectSettings) and new link path (F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ProjectSettings)
Executing 'mklink /J "F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ModdingGam-Windows\ProjectSettings" "F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ProjectSettings"'
Failed to initialize project 'ModdingGameClient' for platform 'Windows'.
Failed during task:  initializing new project ModdingGameClient (Windows) (Took 0.1 seconds, time: 14:08:02, total elapsed: 0.6 seconds)
Failed during task:  updating package directories for project ModdingGameClient (Took 0.1 seconds, time: 14:08:02, total elapsed: 0.6 seconds)
Failed during task:  initializing new project "ModdingGameClient" (Took 0.6 seconds, time: 14:08:02, total elapsed: 0.6 seconds)
'utf-8' codec can't decode byte 0x81 in position 21: invalid start byte

Traceback (most recent call last):
  File "C:\Projects\ModestTree\projeny\Source\mtm\util\ScriptRunner.py", line 18, in runWrapper
  File "C:\Projects\ModestTree\projeny\Source\prj\main\PrjRunner.py", line 171, in _runInternal
  File "C:\Projects\ModestTree\projeny\Source\prj\main\PrjRunner.py", line 78, in _runPreBuild
  File "C:\Projects\ModestTree\projeny\Source\prj\main\PackageManager.py", line 115, in createProject
  File "C:\Projects\ModestTree\projeny\Source\prj\main\PackageManager.py", line 149, in updateProjectJunctions
  File "C:\Projects\ModestTree\projeny\Source\prj\main\PackageManager.py", line 365, in checkProjectInitialized
  File "C:\Projects\ModestTree\projeny\Source\prj\main\PackageManager.py", line 471, in _initNewProjectForPlatform
  File "C:\Projects\ModestTree\projeny\Source\mtm\util\JunctionHelper.py", line 44, in makeJunction
  File "C:\Projects\ModestTree\projeny\Source\mtm\util\SystemHelper.py", line 88, in executeShellCommand
  File "C:\Projects\ModestTree\projeny\Source\mtm\util\ProcessRunner.py", line 107, in execShellCommand
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 21: invalid start byte

Operation completed with errors.  Took 0.6 seconds.
```


Now i executed the following commands

```
F:\Dateien\Unity\Projekte>prj -cc
Initializing new projeny config

F:\Dateien\Unity\Projekte>prj --project ModdingGameClient --createProject

Initializing new project "ModdingGameClient"...
   Updating package directories for project ModdingGameClient...
      Project "ModdingGameClient" is not initialized for platform "Windows".  Initializing now.
      Initializing new project ModdingGameClient (Windows)...
         Failed to initialize project 'ModdingGameClient' for platform 'Windows'.
      Failed during task:  initializing new project ModdingGameClient (Windows) (Took 0.1 seconds, time: 14:08:02, total elapsed: 0.6 seconds)
   Failed during task:  updating package directories for project ModdingGameClient (Took 0.1 seconds, time: 14:08:02, total elapsed: 0.6 seconds)
Failed during task:  initializing new project "ModdingGameClient" (Took 0.6 seconds, time: 14:08:02, total elapsed: 0.6 seconds)
'utf-8' codec can't decode byte 0x81 in position 21: invalid start byte
Operation completed with errors.  Took 0.6 seconds.

F:\Dateien\Unity\Projekte>
```

**Comment by svermeulen** [comment] 2016-02-20 13:11
Can you attach the PrjLog.txt file?  Should be in the same directory you are running `prj`

**Comment by MegaThorx** [comment] 2016-02-20 13:13
[PrjLog.txt](https://github.com/modesttree/Projeny/files/139135/PrjLog.txt)

I already posted it up there but here as an attachment

**Comment by svermeulen** [comment] 2016-02-20 13:18
What version of windows?

**Comment by MegaThorx** [comment] 2016-02-20 13:19
Windows 8.1 Pro

**Comment by svermeulen** [comment] 2016-02-20 13:21
That's probably related.  I only tested on Windows 7 unfortunately.    It's failing when it tries to create the directory junctions.  What happens when you run this directly yourself?

    mklink /J "F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ModdingGam-Windows\ProjectSettings" "F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ProjectSettings"

**Comment by MegaThorx** [comment] 2016-02-20 13:23
Does already exist. I deleted and recreated it with the command. Without any problems.

**Comment by svermeulen** [comment] 2016-02-20 13:23
What's the output from that command?  It's failing when it parses that

**Comment by MegaThorx** [comment] 2016-02-20 13:24
`Verbindung erstellt für F:\Dateien\Unity\Projekte\UnityProjects\ModdingGameClient\ModdingGamWindows\ProjectSettings <<===>> F:\Dateien\Unity\Projekte\UnityProects\ModdingGameClient\ProjectSettings`

**Comment by svermeulen** [comment] 2016-02-20 13:25
Ah it's the "ü" character for some reason.

**Comment by svermeulen** [comment] 2016-02-20 13:26
Are you running from source or exe?

**Comment by MegaThorx** [comment] 2016-02-20 13:26
I'm running from exe

**Comment by svermeulen** [comment] 2016-02-20 13:29
This is a longshot but can you try running `set PYTHONIOENCODING=utf8` in console then running the `prj` again?

**Comment by MegaThorx** [comment] 2016-02-20 13:30
Same error again

**Comment by svermeulen** [comment] 2016-02-20 13:30
Ok, I have a VM of windows 8, I'll try and repro it myself

**Comment by MegaThorx** [comment] 2016-02-20 13:37
Well i think the problem is the language. I will change it to english and test it again

**Comment by MegaThorx** [comment] 2016-02-20 13:40
```
F:\Dateien\Unity\Projekte>prj --init

Initializing project "ModdingGameClient"...
   Updating package directories for project ModdingGameClient...
      Finished updating packages for project "ModdingGameClient"
   Finished updating package directories for project ModdingGameClient (Took 0.2 seconds, time: 14:39:52, total elapsed: 0.2 seconds)
   Successfully initialized project "ModdingGameClient"
Finished initializing project "ModdingGameClient" (Took 0.2 seconds, time: 14:39:52, total elapsed: 0.2 seconds)
Operation completed successfully.  Took 0.2 seconds.
```

After i changed the system language to english

**Comment by MegaThorx** [comment] 2016-02-20 13:44
And change project results in a crash if the other project isn't initlized by unity

**Comment by svermeulen** [comment] 2016-02-20 13:45
It should initialize on first open.  Can you post the log?

**Comment by MegaThorx** [comment] 2016-02-20 13:47
[PrjLog.txt](https://github.com/modesttree/Projeny/files/139152/PrjLog.txt)
And nothing happens at this point. Unity freezes at the old project

**Comment by svermeulen** [comment] 2016-02-20 14:28
I can't reproduce either of these issues.  Can you provide repro-steps for the freeze you're talking about starting from creating an initial config?

**Comment by MegaThorx** [comment] 2016-02-20 14:54
I set my system language to english
Created the config "prj -cc"
Created a project "prj --project Test --createProject"
Opened the project with unity
Created a second project "prj --project TestSecond --createProject"
Clicked the refresh thing and waited until i can change to project with projeny
After this it freezed

You couldn't reproduce the utf8 thing? Did you change the system language to german?

Does projeny depend on some 3d-party stuff?

**Comment by svermeulen** [comment] 2016-02-20 17:40
Ok, changing to german allowed me to reproduce the utf8 issue so I'll fix that.  Before that I was just outputting the bad character manually.

But no luck on the second issue.  I'll try it with windows 8

**Comment by svermeulen** [comment] 2016-02-20 17:40
Projeny depends on some python libraries, but those should all be packaged in if you're using the exe build

**Comment by MegaThorx** [comment] 2016-02-20 18:14
` output = stdoutData.decode(encoding='utf-8',errors='ignore').strip()`

I changed the line of ProcessRunner.py in mtm/util to the upper line and i have no error :P

**Comment by svermeulen** [comment] 2016-02-20 18:15
Oh are you running from source now?

This should be fixed in commit 009a20a240467bf068ec37549578c6df5ccbdafb

**Comment by MegaThorx** [comment] 2016-02-20 18:19
Yeah i downloaded it 30 minutes ago

**Comment by MegaThorx** [comment] 2016-03-22 17:30
```
PrjCommandException: Error occurred during 'Updating directory links': 'charmap' codec can't decode byte 0x81 in position 21: character maps to <undefined>

Projeny.Internal.PrjCommandHandler+<ProcessPrjCommand>d__3.MoveNext ()
Projeny.Internal.CoRoutine.Pump ()
Rethrow as CoRoutineException: Coroutine Object Trace: PmProjectViewHandler -> PrjCommandHandler
Projeny.Internal.CoRoutine.Pump ()
Projeny.Internal.AsyncProcessor.AdvanceFrameAll ()
Rethrow as AsyncOperationException: Error occurred during async operation
Projeny.Internal.AsyncProcessor.AdvanceFrameAll ()
Projeny.Internal.AsyncProcessor.Tick ()
Projeny.Internal.PmCompositionRoot.Update ()
Projeny.Internal.PmWindow.Update ()
UnityEngine.Debug:LogException(Exception)
Projeny.Internal.Log:ErrorException(Exception)
Projeny.Internal.PmWindow:OnErrorOccurred(Exception)
Projeny.Internal.PmWindow:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

```

Well with your fix 009a20a you generate the following error.

ProcessRunner.py on line 108 works fine

```
        output = stdoutData.decode(encoding='utf-8',errors='ignore').strip()
        errors = stderrData.decode(encoding='utf-8',errors='ignore').strip()
```

**Comment by svermeulen** [comment] 2016-04-01 22:53
So you're saying that my fix 009a20a didn't work for you and I should change it to those lines instead?

I wonder if this would solve it too:

        output = stdoutData.decode(sys.stdout.encoding, errors='ignore').strip()
        errors = stderrData.decode(sys.stderr.encoding, errors='ignore').strip()

Would you mind trying that?  I am not seeing this error.

**Comment by MegaThorx** [comment] 2016-04-05 18:31
```
    output = stdoutData.decode(encoding=sys.stdout.encoding, errors='ignore').strip()
    errors = stderrData.decode(encoding=sys.stderr.encoding, errors='ignore').strip()
```

Yes this works fine.

**Comment by svermeulen** [comment] 2016-04-05 18:38
Ok great.  Thanks.

**Closed by svermeulen** 2016-04-05 18:38 UTC

**Comment by mfdeveloper** [comment] 2016-04-22 19:05
Hello @svermeulen. I have the same situation now. Do you push this fix into the last release tag `0.3.3`? I'm using Windows 7 with Brasilian language and I got the same utf-8 error :(

**Comment by svermeulen** [comment] 2016-04-22 19:20
Oh, oops, I didn't make a release for this fix.  I'll do that today.   If you don't want to wait for that you can install by source which should have the fix.

**Comment by svermeulen** [comment] 2016-04-23 16:49
Ok I made a new [release](https://github.com/modesttree/Projeny/releases/tag/v0.3.4).  If you end up trying it, let me know if it addresses your issue
